.PHONY: all clean

all:
	$(MAKE) -C aes_test
	$(MAKE) -C basic
	$(MAKE) -C server
	$(MAKE) -C openssl_test

clean:
	$(MAKE) -C aes_test clean
	$(MAKE) -C basic clean
	$(MAKE) -C server clean
	$(MAKE) -C openssl_test clean
